# Generated by Django 4.1.6 on 2023-02-03 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_query_date_of_creation"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Processing Query", "Processing Query"),
                    ("Resolved", "Resolved"),
                    ("Rejected", "Rejected"),
                ],
                max_length=100,
            ),
        ),
    ]
