# Generated by Django 4.1.6 on 2023-02-03 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_query_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
