# Generated by Django 4.1.6 on 2023-02-12 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_query_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="query",
            name="event_name",
            field=models.CharField(max_length=200, null=True),
        ),
    ]
