# Generated by Django 4.1.6 on 2023-02-14 13:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_query_event_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="query",
            old_name="transaction_id",
            new_name="order_id",
        ),
    ]
